# Generated by Django 2.1.5 on 2023-07-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20230730_2306'),
        ('blogging', '0003_auto_20230730_1944'),
    ]

    operations = [
    ]
